# Generated by Django 5.2.6 on 2025-10-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0002_alter_bank_id_alter_bank_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bank",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
