# Generated by Django 5.2.6 on 2025-09-15 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsorships", "0003_alter_sponsorship_user_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sponsorship",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="sponsorship",
            name="user_sponsor",
        ),
        migrations.AddField(
            model_name="sponsorship",
            name="sponsor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_sponsorships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sponsorship",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sponsored_by_me",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
