# Generated by Django 5.2.6 on 2025-09-19 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsorships", "0007_alter_sponsorship_sponsor_alter_sponsorship_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sponsorship",
            name="user_level",
        ),
        migrations.AddIndex(
            model_name="sponsorship",
            index=models.Index(
                fields=["sponsor"], name="sponsorship_sponsor_dfdf61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorship",
            index=models.Index(fields=["user"], name="sponsorship_user_id_37a3c1_idx"),
        ),
    ]
