# Generated by Django 5.2.6 on 2025-09-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="ktp",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
