# Generated by Django 5.2.6 on 2025-09-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_sponsor_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="sponsor_username",
        ),
    ]
