# Generated by Django 5.2.6 on 2025-09-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_customuser_sponsor_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="ahliwaris",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
