# Generated by Django 5.2.6 on 2025-09-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_ahliwaris"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="level_status",
            field=models.CharField(
                choices=[
                    ("AGA", "Agent"),
                    ("SPP", "Senior Supervisor"),
                    ("SM", "Senior Manager"),
                    ("SD", "Senior Director"),
                ],
                default="AGA",
                max_length=3,
            ),
        ),
    ]
