# Generated by Django 5.2.6 on 2025-09-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="ktp",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
