# Generated by Django 5.2.6 on 2025-09-14 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_customuser_ktp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="sponsor_id",
            field=models.ForeignKey(
                blank=True,
                db_column="sponsor_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referred_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
