# Generated by Django 5.2.6 on 2025-09-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_customuser_sponsor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="level_status",
            field=models.CharField(
                choices=[("AGA", "Agent"), ("SPV", "Supervisor"), ("DRC", "Director")],
                default="AGA",
                max_length=3,
            ),
        ),
    ]
