# Generated by Django 5.2.6 on 2025-10-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nasabah", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nasabah",
            old_name="name",
            new_name="nasabah_name",
        ),
    ]
